### ISSUE TITLE
Proposal: merge this repo into github.com/pion/rtp/io

### ISSUE THREAD

**Issue by stv0g** [pion/rtpio#12]
This would reduce the maintenance overhead

**Comment by stv0g** [comment]
@kevmo314 What do you think about it?

I would volunteer to do the migration

**Comment by kevmo314** [comment]
> @kevmo314 What do you think about it?
> 
> I would volunteer to do the migration

Sounds good to me, I can approve the pion/rtp PR for you :)

**Comment by stv0g** [comment]
I started to create a PR for the merge, but then realized that rtpio also depends on pion/rtcp.
So we better keep it separate as I dont like pulling rtcp into the rtp module.
